#!/usr/bin/env python

import matplotlib.pyplot as plt
from matplotlib.widgets import Slider, Button
import numpy as np
import matplotlib.animation as animation

from palette.OkTools import *

"""
thanks for chat gee pee tee for this absolute mess of a script

Playback snapshots of ParticleSim generated by PaletteGenerator
watch points wiggle or smth
"""

oklab_frame_list = np.load('output/cloudHistogram.npy', allow_pickle=True)

# Convert all frames to sRGB for plotting
srgb_frames = []
for frame in oklab_frame_list:
	rgb_frame = oklabToSrgb(np.array(frame))
	rgb_frame = np.clip(rgb_frame,[0]*3,[1]*3)
	srgb_frames.append(np.array(rgb_frame))


# Initial plot
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

sc = ax.scatter(
    oklab_frame_list[0][:, 0], oklab_frame_list[0][:, 1], oklab_frame_list[0][:, 2],
    s=64, depthshade=True, facecolors=srgb_frames[0], edgecolors='k', linewidths=0.3
)

ax.set_xlabel('L')
ax.set_ylabel('a')
ax.set_zlabel('b')

# --- Slider

# Slider axis
ax_slider = plt.axes([0.2, 0.02, 0.4, 0.03], facecolor='lightgoldenrodyellow')

frame_count = len(oklab_frame_list)
slider = Slider(ax_slider, 'Frame', 0, max(1, frame_count - 1), valinit=0, valstep=1)
if frame_count <= 1:
    slider = Slider(ax_slider, 'Frame', 0, 1, valinit=0, valstep=1)
    slider.valtext.set_visible(False)
    slider.ax.set_visible(False)

# Compute global ranges

L_min, L_max = 0.0,1.0
a_min, a_max = -0.32,0.32
b_min, b_max = -0.32,0.32

ax.set_xlim(L_min, L_max)
ax.set_ylim(a_min, a_max)
ax.set_zlim(b_min, b_max)


# --- play button

def update(val):
    idx = int(slider.val)
    sc._offsets3d = (oklab_frame_list[idx][:, 0], oklab_frame_list[idx][:, 1], oklab_frame_list[idx][:, 2])
    sc.set_facecolors(srgb_frames[idx])
    fig.canvas.draw_idle()

slider.on_changed(update)

# Play button
ax_play = plt.axes([0.82, 0.02, 0.1, 0.03])
btn_play = Button(ax_play, 'Play')

ani = None  # animation created on first play
playing = False
interval_ms = 3000.0 / max(1, frame_count)

def advance_frame(frame_index):
    sc._offsets3d = (oklab_frame_list[frame_index][:, 0],
                      oklab_frame_list[frame_index][:, 1],
                      oklab_frame_list[frame_index][:, 2])
    sc.set_facecolors(srgb_frames[frame_index])
    slider.set_val(frame_index)

def toggle_play(event):
    global ani, playing
    if not playing:
        if ani is None:
            ani = animation.FuncAnimation(
                fig,
                advance_frame,
                frames=range(frame_count),
                interval=interval_ms,
                blit=False,
                repeat=True,
                cache_frame_data=False
            )
        ani.event_source.start()
        fig.canvas.draw_idle()
        btn_play.label.set_text("Pause")
        playing = True
    else:
        if ani is not None:
            ani.event_source.stop()
        btn_play.label.set_text("Play")
        playing = False

btn_play.on_clicked(toggle_play)

advance_frame(0)
fig.canvas.draw_idle()
plt.show()
